
# from
# https://fishandwhistle.net/post/2016/using-pyserial-pynmea2-and-raspberry-pi-to-log-nmea-output/

talkers <-  c(
  'AG' = 'Autopilot(General)',
  'AP' = 'Autopilot(Magnetic)',
  'CC' = 'Programmed Calculator',
  'CD' = 'DSC (Digital Selective Calling)',
  'CM' = 'Memory Data',
  'CS' = 'Satellite Communications',
  'CT' = 'Radio-Telephone (MF/HF)',
  'CV' = 'Radio-Telephone (VHF)',
  'CX' = 'Scanning Receiver',
  'DE' = 'DECCA Navigation',
  'DF' = 'Direction Finder',
  'DM' = 'Magnetic Water Velocity Sensor',
  'EC' = 'ECDIS (Electronic Chart Display & Information System)',
  'EP' = 'EPIRB (Emergency Position Indicating Beacon)',
  'ER' = 'Engine Room Monitoring Systems',
  'GP' = 'GPS',
  'HC' = 'Magnetic Compass',
  'HE' = 'North Seeking Gyro',
  'HN' = 'Non-North Seeking Gyro',
  'II' = 'Integrated Instrumentation',
  'IN' = 'Integrated Navigation',
  'LA' = 'Loran A',
  'LC' = 'Loran C',
  'MP' = 'Microwave Positioning System',
  'OM' = 'OMEGA Navigation System',
  'OS' = 'Distress Alarm System',
  'RA' = 'RADAR and/or ARPA',
  'SD' = 'Depth Sounder',
  'SN' = 'Electronic Positioning System',
  'SS' = 'Scanning Sounder',
  'TI' = 'Turn Rate Indicator',
  'TR' = 'TRANSIT Navigation System',
  'VD' = 'Doppler Velocity Sensor',
  'VW' = 'Mechanical Water Velocity Sensor',
  'WI' = 'Weather Instruments',
  'YC' = 'Temperature Transducer',
  'YD' = 'Displacement Transducer',
  'YF' = 'Frequency Transducer',
  'YL' = 'Level Transducer',
  'YP' = 'Pressure Transducer',
  'YR' = 'Flow Rate Transducer',
  'YT' = 'Tachometer Transducer',
  'YV' = 'Volume Transducer',
  'YX' = 'Transducer',
  'ZA' = 'Atomic Clock Timekeeper',
  'ZC' = 'Chronometer Timekeeper',
  'ZQ' = 'Quartz Clock Timekeeper',
  'ZV' = 'Radio Update Timekeeper'
)

messages <- c(
  'GNS' = 'Fix data',
  'DPT' = 'Depth of Water',
  'GST' = 'GPS Pseudorange Noise Statistics',
  'DTM' = 'Datum Reference',
  'GSV' = 'Satellites in view',
  'AAM' = 'Waypoint Arrival Alarm',
  'FSI' = 'Frequency Set Information',
  'VHW' = 'Water speed and heading',
  'GLC' = 'Geographic Position, Loran-C',
  'MSS' = 'Beacon Receiver Status',
  'PASHR' = 'RT300 proprietary roll and pitch sentence',
  'GSA' = 'GPS DOP and active satellites',
  'VDR' = 'Set and Drift',
  'MSK' = 'Control for a Beacon Receiver',
  'GBS' = 'GPS Satellite Fault Detection',
  'TPC' = 'Trawl Position Cartesian Coordinates',
  'HFB' = 'Trawl Headrope to Footrope and Bottom',
  'ZTG' = 'UTC & Time to Destination Waypoint',
  'MWV' = 'Wind Speed and Angle',
  'DCN' = 'Decca Position',
  'HSC' = 'Heading Steering Command',
  'PUBX 00' = 'uBlox Lat/Long Position Data',
  'PRWIZCH' = 'Rockwell Channel Status',
  'OLN' = 'Omega Lane Numbers',
  'RMB' = 'Recommended Minimum Navigation Information',
  'RMC' = 'Recommended Minimum Navigation Information',
  'RMA' = 'Recommended Minimum Navigation Information',
  'GGA' = 'Global Positioning System Fix Data',
  'TTM' = 'Tracked Target Message',
  'PGRME' = 'Garmin Estimated Error',
  'ROT' = 'Rate Of Turn',
  'OSD' = 'Own Ship Data',
  'VLW' = 'Distance Traveled through Water',
  'WPL' = 'Waypoint Location',
  'PUBX 01' = 'uBlox UTM Position Data',
  'RTE' = 'Routes',
  'GTD' = 'Geographic Location in Time Differences',
  'GRS' = 'GPS Range Residuals',
  'VTG' = 'Track made good and Ground speed',
  'WCV' = 'Waypoint Closure Velocity',
  'PMGNST' = 'Magellan Status',
  'STN' = 'Multiple Data ID',
  'MTW' = 'Mean Temperature of Water',
  'TRF' = 'TRANSIT Fix Data',
  'TDS' = 'Trawl Door Spread Distance',
  'XTE' = 'Cross-Track Error, Measured',
  'TPT' = 'Trawl Position True',
  'TPR' = 'Trawl Position Relative Vessel',
  'PUBX 03' = 'uBlox Satellite Status',
  'R00' = 'Waypoints in active route',
  'DBK' = 'Depth Below Keel',
  'ALM' = 'GPS Almanac Data',
  'TFI' = 'Trawl Filling Indicator',
  'PUBX 04' = 'uBlox Time of Day and Clock Information',
  'RSD' = 'RADAR System Data',
  'RPM' = 'Revolutions',
  'RSA' = 'Rudder Sensor Angle',
  'VWR' = 'Relative Wind Speed and Angle',
  'ITS' = 'Trawl Door Spread 2 Distance',
  'LCD' = 'Loran-C Signal Data',
  'SFI' = 'Scanning Frequency Information',
  'APB' = 'Autopilot Sentence "B"',
  'VBW' = 'Dual Ground/Water Speed',
  'DBS' = 'Depth Below Surface',
  'APA' = 'Autopilot Sentence "A"',
  'DBT' = 'Depth below transducer',
  'ZFO' = 'UTC & Time from origin Waypoint'
)

nmea_talkers <- as.data.frame(tibble::enframe(talkers, "talker", "talker_label"))
nmea_message_types <- as.data.frame(tibble::enframe(messages, "message_type", "message_type_label"))

usethis::use_data(nmea_talkers, overwrite = TRUE)
usethis::use_data(nmea_message_types, overwrite = TRUE)
