# Generated by cpp11: do not edit by hand

cpp_nmea_as_character <- function(nmea, ascii) {
  .Call(`_nmea_cpp_nmea_as_character`, nmea, ascii)
}

cpp_nmea_parse_sentences <- function(obj, skip, n_max, sentence_max_length) {
  invisible(.Call(`_nmea_cpp_nmea_parse_sentences`, obj, skip, n_max, sentence_max_length))
}
